# Generated by Django 4.2.5 on 2023-10-03 06:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="upc",
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]
