# Generated by Django 4.2.5 on 2023-10-03 07:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_item_upc"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vendor",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
