# Generated by Django 4.2.5 on 2023-12-22 06:21

import apps.products.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0003_remove_category_is_active_remove_product_is_active"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="vendor",
            options={"verbose_name": "Поставщик / Вендор /", "verbose_name_plural": "Поставщики / Вендоры /"},
        ),
        migrations.CreateModel(
            name="ItemImage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("image", models.ImageField(upload_to=apps.products.models.upload_image_path)),
                ("is_main", models.BooleanField(default=False)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="images", to="products.item"
                    ),
                ),
            ],
        ),
    ]
