# Generated by Django 4.2.5 on 2023-12-24 06:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0005_alter_itemimage_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="itemimage",
            options={},
        ),
    ]
