# Generated by Django 4.2.5 on 2023-11-03 07:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0002_alter_order_options_alter_orderrow_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("новый", "новый"),
                    ("в доставке", "в доставке"),
                    ("завершен", "завершен"),
                    ("отменен", "отменен"),
                ],
                default="новый",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
