# Generated by Django 4.2.5 on 2023-11-13 07:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0003_order_status_order_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("STATUS_NEW", "новый"),
                    ("STATUS_DELIVERY", "в доставке"),
                    ("STATUS_FINISHED", "завершен"),
                    ("STATUS_CANCELED", "отменен"),
                ],
                default="STATUS_NEW",
                max_length=30,
            ),
        ),
    ]
