# Generated by Django 4.2.5 on 2023-12-22 06:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0004_alter_order_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={"verbose_name": "Покупка / Заказ", "verbose_name_plural": "Покупки / Заказы"},
        ),
        migrations.AlterModelOptions(
            name="orderrow",
            options={"verbose_name": "Покупка / Заказ", "verbose_name_plural": "Покупки / Заказы"},
        ),
    ]
