version: "3.3"

networks:
  private:

volumes:
  pg_data:
  redis_data:

services:
  db:
    image: postgres:alpine
    restart: always
    env_file:
      - .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  redis:
    image: redis:alpine
    volumes:
      - redis_data:/data
    ports:
      - 6379:6379

