# Загрузка файлов через название в строке запроса
POST http://localhost:8000/api/v1/products-import-data/?file_name=import_1.csv
Content-Type: application/json
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjk4NjQyNzM3LCJpYXQiOjE2OTgwMzc5MzcsImp0aSI6ImNkNzAxODZiMmM2MjQwNWY5NTFkZGVhZmFhYjRkMzY2IiwidXNlcl9pZCI6MX0.5TELhyAiz6YW-xFpmnkvwJUZBOoObK7DL3CsSXDiQvk

###
# Загрузка файла через Postman

POST http://localhost:8000/api/v1/products-import-file/
Content-Type: application/json
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjk4NjMwNzU5LCJpYXQiOjE2OTgwMjU5NTksImp0aSI6IjRjNmFkNGUyMTg5ZDQ4OGRhMGM0MjVmMWMyMmI3NmI1IiwidXNlcl9pZCI6MX0.AZDrXdCN7583aDXYmW0190tuUmK-IzM5Rh-cRX-HLYk


###
# Создание Юзера
POST http://localhost:8000/api/v1/auth/users/
Content-Type: application/json

{
  "email": "admin2@admin.org",
  "password": "develop123"
}

###
# Создание токена
POST http://localhost:8000/api/v1/auth/jwt/create/
Content-Type: application/json

{
  "email": "admin@admin.org",
  "password": "admin"
}

###
# Проверка данных Юзера

GET http://localhost:8000/api/v1/auth/users/me/
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjk4MTI1MDgyLCJpYXQiOjE2OTc1MjAyODIsImp0aSI6ImU3OGNmMTEzZWZlMjRjMGJhYjRjNjc1NWY0ZDU3ZmM4IiwidXNlcl9pZCI6Mn0.uibsUDzO3LfK-9kD8TMIlfX39fCTX2vz6JaDwS_AiQo

###

GET http://localhost:8000/api/v1/items/
Content-Type: application/json
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjk4NjMwNzU5LCJpYXQiOjE2OTgwMjU5NTksImp0aSI6IjRjNmFkNGUyMTg5ZDQ4OGRhMGM0MjVmMWMyMmI3NmI1IiwidXNlcl9pZCI6MX0.AZDrXdCN7583aDXYmW0190tuUmK-IzM5Rh-cRX-HLYk

###

GET http://localhost:8000/api/v1/items/?limit=5&ordering=-price&product__category=1&search=XS
Content-Type: application/json
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjk4MzAwNjQxLCJpYXQiOjE2OTc2OTU4NDEsImp0aSI6IjhiZGM4NTQ4NzM2ZjRlMjlhNmEyODc5NWM1MjkzNDE4IiwidXNlcl9pZCI6MX0.UiCfPYMGGo8VyEzKaxeXBsJLDNkKndzJgPd2h2FGB6Y

###

POST http://localhost:8000/api/v1/basket-rows/
Content-Type: application/json
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjk4NjMwNzU5LCJpYXQiOjE2OTgwMjU5NTksImp0aSI6IjRjNmFkNGUyMTg5ZDQ4OGRhMGM0MjVmMWMyMmI3NmI1IiwidXNlcl9pZCI6MX0.AZDrXdCN7583aDXYmW0190tuUmK-IzM5Rh-cRX-HLYk

{
  "item_id": 100
}

###