# Создание юзера
POST http://localhost:8000/api/v1/auth/users/
Content-Type: application/json

{
  "email": "admin2@admin.org",
  "password": "develop123"
}

###
# Создание токена

POST http://localhost:8000/api/v1/auth/jwt/create/
Content-Type: application/json

{
  "email": "admin2@admin.org",
  "password": "develop123"
}

###

GET http://localhost:8000/api/v1/auth/users/me/
Authorization: JWT [TOKEN]

###

POST http://localhost:8000/api/v1/import-data/?file_type=yml
Content-Type: application/json
Authorization: JWT [TOKEN]
