# docker build -t api .
# docker-compose up -d


# Push in DickerHub:
# docker build -t antuanuran/name .
# docker push antuanuran/name:latest
# docker pull antuanuran/name


### Вывод всех имеющихся товаров. GET-запрос. (Для просмотра можно без авторизации)
GET http://localhost/api/v1/items/
