# Generated by Django 4.2.5 on 2023-09-18 08:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "Покупатель", "verbose_name_plural": "Покупатели"},
        ),
    ]
