# Generated by Django 4.2.5 on 2023-11-13 03:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_user_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "Менеджер", "verbose_name_plural": "Менеджеры"},
        ),
    ]
