# Generated by Django 4.2.5 on 2023-12-22 06:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_user_is_customer"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "Менеджер / Покупатель", "verbose_name_plural": "Менеджеры / Покупатели"},
        ),
    ]
