# Generated by Django 4.2.5 on 2023-10-19 07:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("products", "0003_alter_vendor_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Basket",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
            ],
        ),
        migrations.CreateModel(
            name="BasketRow",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("qty", models.PositiveIntegerField(default=1)),
                (
                    "basket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="rows", to="basket.basket"
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="basket_rows", to="products.item"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="basket",
            name="items",
            field=models.ManyToManyField(
                blank=True, related_name="baskets", through="basket.BasketRow", to="products.item"
            ),
        ),
        migrations.AddField(
            model_name="basket",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="baskets", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
