# Generated by Django 4.2.5 on 2023-10-23 04:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("basket", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="basketrow",
            options={"verbose_name": "Корзина", "verbose_name_plural": "Корзины"},
        ),
        migrations.AddField(
            model_name="basket",
            name="name",
            field=models.CharField(max_length=64, null=True, unique=True),
        ),
    ]
