# Generated by Django 4.2.5 on 2023-10-23 04:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("basket", "0002_alter_basketrow_options_basket_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="basket",
            name="name",
        ),
    ]
