# Generated by Django 4.2.5 on 2023-11-03 05:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("basket", "0003_remove_basket_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="basket",
            options={"verbose_name": "Корзина", "verbose_name_plural": "Корзины"},
        ),
        migrations.AlterModelOptions(
            name="basketrow",
            options={"verbose_name": "Заказ в корзине", "verbose_name_plural": "Заказы в корзине"},
        ),
    ]
