# Generated by Django 4.2.5 on 2023-12-22 06:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("basket", "0003_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="basket",
            options={"verbose_name": "Корзина товаров", "verbose_name_plural": "Корзина товаров"},
        ),
        migrations.AlterModelOptions(
            name="basketrow",
            options={"verbose_name": "Заказ в корзине ", "verbose_name_plural": "Заказы в корзине"},
        ),
    ]
